import type { SchemaIR, TableIR, ColumnIR } from '@/ir/types';

/**
 * İstenen hedef veritabanı için tip eşleme fonksiyonu. Bu fonksiyon, IR'deki basit tipleri
 * hedef veritabanı dialektine çevirir. Daha karmaşık tipler gerektiğinde genişletilebilir.
 */
function mapType(col: ColumnIR, target: string): string {
  switch (target) {
    case 'mssql': {
      switch (col.type) {
        case 'int':
          return 'INT';
        case 'bigint':
          return 'BIGINT';
        case 'numeric':
          return `DECIMAL(${col.precision ?? 18}, ${col.scale ?? 0})`;
        case 'bool':
          return 'BIT';
        case 'varchar':
          return col.length && col.length > 0 ? `VARCHAR(${col.length})` : 'VARCHAR(MAX)';
        case 'nvarchar':
          return col.length && col.length > 0 ? `NVARCHAR(${col.length})` : 'NVARCHAR(MAX)';
        case 'text':
          return 'NVARCHAR(MAX)';
        case 'date':
          return 'DATE';
        case 'datetime':
        case 'timestamp':
          return 'DATETIME2';
        case 'json':
          return 'NVARCHAR(MAX)';
        case 'binary':
          return 'VARBINARY(MAX)';
        case 'uuid':
          return 'UNIQUEIDENTIFIER';
        default:
          return 'NVARCHAR(MAX)';
      }
    }
    case 'postgresql': {
      switch (col.type) {
        case 'int':
          return 'INTEGER';
        case 'bigint':
          return 'BIGINT';
        case 'numeric':
          return `NUMERIC(${col.precision ?? 18}, ${col.scale ?? 0})`;
        case 'bool':
          return 'BOOLEAN';
        case 'varchar':
          return col.length && col.length > 0 ? `VARCHAR(${col.length})` : 'TEXT';
        case 'nvarchar':
          return col.length && col.length > 0 ? `VARCHAR(${col.length})` : 'TEXT';
        case 'text':
          return 'TEXT';
        case 'date':
          return 'DATE';
        case 'datetime':
        case 'timestamp':
          return 'TIMESTAMP';
        case 'json':
          return 'JSONB';
        case 'binary':
          return 'BYTEA';
        case 'uuid':
          return 'UUID';
        default:
          return 'TEXT';
      }
    }
    case 'mysql': {
      switch (col.type) {
        case 'int':
          return 'INT';
        case 'bigint':
          return 'BIGINT';
        case 'numeric':
          return `DECIMAL(${col.precision ?? 18}, ${col.scale ?? 0})`;
        case 'bool':
          return 'TINYINT(1)';
        case 'varchar':
          return col.length && col.length > 0 ? `VARCHAR(${col.length})` : 'TEXT';
        case 'nvarchar':
          return col.length && col.length > 0 ? `NVARCHAR(${col.length})` : 'LONGTEXT';
        case 'text':
          return 'LONGTEXT';
        case 'date':
          return 'DATE';
        case 'datetime':
        case 'timestamp':
          return 'DATETIME';
        case 'json':
          return 'JSON';
        case 'binary':
          return 'BLOB';
        case 'uuid':
          return 'CHAR(36)';
        default:
          return 'LONGTEXT';
      }
    }
    case 'oracle': {
      switch (col.type) {
        case 'int':
        case 'bigint':
          return 'NUMBER';
        case 'numeric':
          return `NUMBER(${col.precision ?? 18}, ${col.scale ?? 0})`;
        case 'bool':
          return 'NUMBER(1)';
        case 'varchar':
        case 'nvarchar':
          return col.length && col.length > 0 ? `VARCHAR2(${col.length})` : 'CLOB';
        case 'text':
          return 'CLOB';
        case 'date':
          return 'DATE';
        case 'datetime':
        case 'timestamp':
          return 'TIMESTAMP';
        case 'json':
          return 'CLOB';
        case 'binary':
          return 'BLOB';
        case 'uuid':
          return 'RAW(16)';
        default:
          return 'CLOB';
      }
    }
    default:
      throw new Error(`Unsupported target for type mapping: ${target}`);
  }
}

/**
 * Verilen SchemaIR nesnesini ve hedef veritabanı tipini kullanarak CREATE TABLE DDL komutlarını üretir.
 */
export function generateDDL(schema: SchemaIR, target: string): string {
  const statements: string[] = [];
  for (const table of schema.tables) {
    const cols = table.columns.map((col) => {
      const colParts = [] as string[];
      colParts.push(target === 'mssql' ? `[${col.name}]` : `"${col.name}"`);
      colParts.push(mapType(col, target));
      if (!col.nullable) colParts.push('NOT NULL');
      if (col.identity) {
        if (target === 'mssql') colParts.push('IDENTITY(1,1)');
        else if (target === 'postgresql') colParts.push('GENERATED BY DEFAULT AS IDENTITY');
        else if (target === 'mysql') colParts.push('AUTO_INCREMENT');
      }
      if (col.default) {
        colParts.push(`DEFAULT ${col.default}`);
      }
      return colParts.join(' ');
    });
    const parts: string[] = [];
    parts.push(`CREATE TABLE ${target === 'mssql' ? '[' + table.name + ']' : '"' + table.name + '"'} (\n  ${cols.join(',\n  ')}`);
    if (table.primaryKey && table.primaryKey.columns.length > 0) {
      parts.push(`,\n  PRIMARY KEY (${table.primaryKey.columns
        .map((c) => (target === 'mssql' ? '[' + c + ']' : '"' + c + '"'))
        .join(', ')})`);
    }
    parts.push('\n);');
    statements.push(parts.join(''));
  }
  return statements.join('\n\n');
}